// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `types/oculus_controller_state.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct OculusControllerState {
    // message fields
    pub primary_thumbstick: ::protobuf::SingularPtrField<OculusControllerState_Vector2>,
    pub secondary_thumbstick: ::protobuf::SingularPtrField<OculusControllerState_Vector2>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OculusControllerState {
    fn default() -> &'a OculusControllerState {
        <OculusControllerState as ::protobuf::Message>::default_instance()
    }
}

impl OculusControllerState {
    pub fn new() -> OculusControllerState {
        ::std::default::Default::default()
    }

    // .OculusControllerState.Vector2 primary_thumbstick = 1;


    pub fn get_primary_thumbstick(&self) -> &OculusControllerState_Vector2 {
        self.primary_thumbstick.as_ref().unwrap_or_else(|| <OculusControllerState_Vector2 as ::protobuf::Message>::default_instance())
    }
    pub fn clear_primary_thumbstick(&mut self) {
        self.primary_thumbstick.clear();
    }

    pub fn has_primary_thumbstick(&self) -> bool {
        self.primary_thumbstick.is_some()
    }

    // Param is passed by value, moved
    pub fn set_primary_thumbstick(&mut self, v: OculusControllerState_Vector2) {
        self.primary_thumbstick = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_primary_thumbstick(&mut self) -> &mut OculusControllerState_Vector2 {
        if self.primary_thumbstick.is_none() {
            self.primary_thumbstick.set_default();
        }
        self.primary_thumbstick.as_mut().unwrap()
    }

    // Take field
    pub fn take_primary_thumbstick(&mut self) -> OculusControllerState_Vector2 {
        self.primary_thumbstick.take().unwrap_or_else(|| OculusControllerState_Vector2::new())
    }

    // .OculusControllerState.Vector2 secondary_thumbstick = 2;


    pub fn get_secondary_thumbstick(&self) -> &OculusControllerState_Vector2 {
        self.secondary_thumbstick.as_ref().unwrap_or_else(|| <OculusControllerState_Vector2 as ::protobuf::Message>::default_instance())
    }
    pub fn clear_secondary_thumbstick(&mut self) {
        self.secondary_thumbstick.clear();
    }

    pub fn has_secondary_thumbstick(&self) -> bool {
        self.secondary_thumbstick.is_some()
    }

    // Param is passed by value, moved
    pub fn set_secondary_thumbstick(&mut self, v: OculusControllerState_Vector2) {
        self.secondary_thumbstick = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_secondary_thumbstick(&mut self) -> &mut OculusControllerState_Vector2 {
        if self.secondary_thumbstick.is_none() {
            self.secondary_thumbstick.set_default();
        }
        self.secondary_thumbstick.as_mut().unwrap()
    }

    // Take field
    pub fn take_secondary_thumbstick(&mut self) -> OculusControllerState_Vector2 {
        self.secondary_thumbstick.take().unwrap_or_else(|| OculusControllerState_Vector2::new())
    }
}

impl ::protobuf::Message for OculusControllerState {
    fn is_initialized(&self) -> bool {
        for v in &self.primary_thumbstick {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.secondary_thumbstick {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.primary_thumbstick)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.secondary_thumbstick)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.primary_thumbstick.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.secondary_thumbstick.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.primary_thumbstick.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.secondary_thumbstick.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OculusControllerState {
        OculusControllerState::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<OculusControllerState_Vector2>>(
                "primary_thumbstick",
                |m: &OculusControllerState| { &m.primary_thumbstick },
                |m: &mut OculusControllerState| { &mut m.primary_thumbstick },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<OculusControllerState_Vector2>>(
                "secondary_thumbstick",
                |m: &OculusControllerState| { &m.secondary_thumbstick },
                |m: &mut OculusControllerState| { &mut m.secondary_thumbstick },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<OculusControllerState>(
                "OculusControllerState",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static OculusControllerState {
        static instance: ::protobuf::rt::LazyV2<OculusControllerState> = ::protobuf::rt::LazyV2::INIT;
        instance.get(OculusControllerState::new)
    }
}

impl ::protobuf::Clear for OculusControllerState {
    fn clear(&mut self) {
        self.primary_thumbstick.clear();
        self.secondary_thumbstick.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OculusControllerState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OculusControllerState {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct OculusControllerState_Vector2 {
    // message fields
    pub x: f32,
    pub y: f32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OculusControllerState_Vector2 {
    fn default() -> &'a OculusControllerState_Vector2 {
        <OculusControllerState_Vector2 as ::protobuf::Message>::default_instance()
    }
}

impl OculusControllerState_Vector2 {
    pub fn new() -> OculusControllerState_Vector2 {
        ::std::default::Default::default()
    }

    // float x = 1;


    pub fn get_x(&self) -> f32 {
        self.x
    }
    pub fn clear_x(&mut self) {
        self.x = 0.;
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: f32) {
        self.x = v;
    }

    // float y = 2;


    pub fn get_y(&self) -> f32 {
        self.y
    }
    pub fn clear_y(&mut self) {
        self.y = 0.;
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: f32) {
        self.y = v;
    }
}

impl ::protobuf::Message for OculusControllerState_Vector2 {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.x = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.y = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.x != 0. {
            my_size += 5;
        }
        if self.y != 0. {
            my_size += 5;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.x != 0. {
            os.write_float(1, self.x)?;
        }
        if self.y != 0. {
            os.write_float(2, self.y)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OculusControllerState_Vector2 {
        OculusControllerState_Vector2::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "x",
                |m: &OculusControllerState_Vector2| { &m.x },
                |m: &mut OculusControllerState_Vector2| { &mut m.x },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "y",
                |m: &OculusControllerState_Vector2| { &m.y },
                |m: &mut OculusControllerState_Vector2| { &mut m.y },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<OculusControllerState_Vector2>(
                "OculusControllerState.Vector2",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static OculusControllerState_Vector2 {
        static instance: ::protobuf::rt::LazyV2<OculusControllerState_Vector2> = ::protobuf::rt::LazyV2::INIT;
        instance.get(OculusControllerState_Vector2::new)
    }
}

impl ::protobuf::Clear for OculusControllerState_Vector2 {
    fn clear(&mut self) {
        self.x = 0.;
        self.y = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OculusControllerState_Vector2 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OculusControllerState_Vector2 {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#types/oculus_controller_state.proto\"\xe0\x01\n\x15OculusControllerSt\
    ate\x12M\n\x12primary_thumbstick\x18\x01\x20\x01(\x0b2\x1e.OculusControl\
    lerState.Vector2R\x11primaryThumbstick\x12Q\n\x14secondary_thumbstick\
    \x18\x02\x20\x01(\x0b2\x1e.OculusControllerState.Vector2R\x13secondaryTh\
    umbstick\x1a%\n\x07Vector2\x12\x0c\n\x01x\x18\x01\x20\x01(\x02R\x01x\x12\
    \x0c\n\x01y\x18\x02\x20\x01(\x02R\x01yJ\xb2\x02\n\x06\x12\x04\0\0\n\x01\
    \n\x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\n\x01\n\n\
    \n\x03\x04\0\x01\x12\x03\x02\x08\x1d\n\x0c\n\x04\x04\0\x03\0\x12\x04\x04\
    \x02\x07\x03\n\x0c\n\x05\x04\0\x03\0\x01\x12\x03\x04\n\x11\n\r\n\x06\x04\
    \0\x03\0\x02\0\x12\x03\x05\x04\x10\n\x0e\n\x07\x04\0\x03\0\x02\0\x05\x12\
    \x03\x05\x04\t\n\x0e\n\x07\x04\0\x03\0\x02\0\x01\x12\x03\x05\n\x0b\n\x0e\
    \n\x07\x04\0\x03\0\x02\0\x03\x12\x03\x05\x0e\x0f\n\r\n\x06\x04\0\x03\0\
    \x02\x01\x12\x03\x06\x04\x10\n\x0e\n\x07\x04\0\x03\0\x02\x01\x05\x12\x03\
    \x06\x04\t\n\x0e\n\x07\x04\0\x03\0\x02\x01\x01\x12\x03\x06\n\x0b\n\x0e\n\
    \x07\x04\0\x03\0\x02\x01\x03\x12\x03\x06\x0e\x0f\n\x0b\n\x04\x04\0\x02\0\
    \x12\x03\x08\x02!\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x08\x02\t\n\x0c\n\
    \x05\x04\0\x02\0\x01\x12\x03\x08\n\x1c\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\x08\x1f\x20\n\x0b\n\x04\x04\0\x02\x01\x12\x03\t\x02#\n\x0c\n\x05\
    \x04\0\x02\x01\x06\x12\x03\t\x02\t\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\
    \t\n\x1e\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\t!\"b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
